#!/usr/bin/env tcsh

set timeout = 60
set delay = 0
set testcases = (sctp-as-v-1-5-2 \
                 sctp-as-v-1-6-1 \
                 sctp-as-v-1-7-5 \
                 sctp-as-i-1-8-1 \
                 sctp-as-i-1-8-2 \
                 sctp-as-i-1-8-3 \
                 sctp-as-i-1-8-4 \
                 sctp-as-o-1-9-2 \
                 sctp-at-v-2-2   \
                 sctp-at-i-2-11  \
                 sctp-imh-i-3-1  \
                 sctp-imh-i-3-7  \
                 sctp-dm-o-4-7-2 \
                 sctp-fh-v-5-2   \
                 sctp-fh-o-5-3-1 \
                 sctp-d-v-8-3    \
                 sctp-d-v-8-4    \
                 sctp-d-i-8-5    \
                 sctp-d-o-8-7    \
                 sctp-a-v-9-2    \
                 sctp-a-o-9-3    \
                 sctp-m-i-10-1   \
                 sctp-m-i-10-2   \
                 sctp-m-i-10-3   \
                 sctp-m-i-10-4   \
                 sctp-rt-i-11-1  )

foreach testcase ($testcases)
  (runsctptest -t $timeout $testcase > /dev/tty) >& /dev/null
  sleep $delay
end
