#!/usr/bin/env sh

timeout=60
delay=0

testcases='sctp-checksum-crc32c-with-padding
           sctp-checksum-adler32-with-padding
           sctp-checksum-zero-with-padding
           sctp-checksum-wrong-with-padding
           sctp-checksum-crc32c-without-padding
           sctp-checksum-adler32-without-padding
           sctp-checksum-zero-without-padding
           sctp-checksum-wrong-without-padding'

for testcase in $testcases
do
  runsctptest -t $timeout $testcase 2> /dev/null
  sleep $delay
done
